### ISSUE TITLE
Feature Request: Ability to supply an extra DB archive and have it import on install

### ISSUE THREAD

**Issue by scotthooker** [tes/cms-builder#28]
Migrations are fun - I'd like the cms-builder yaml to take a database2 param or "migration-db" param and have it download and import it on build.

**Comment by andriokha** [comment]
Suggestion:
Change
```yaml
database: http://jenkins-native.tescloud.com/view/CMS/job/cms-backup-smart-live/ws/database.sql.gz
```
to
```yaml
databases:
  data: http://jenkins-native.tescloud.com/view/CMS/job/cms-backup-smart-live/ws/database.sql.gz
  migration: database: http://jenkins-native.tescloud.com/mkultra/database.sql.gz
```
Where the key represents the database name?
